#!/usr/bin/env python3

import argparse

from src.logger import LOGGER, LEVEL_WARN
from src.proxy import Proxy
from src.utils import print_banner
from src.parser.error_collector import CompilerException


def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument("source", help="Autoprox config file path.")
    group_verbose = argparser.add_mutually_exclusive_group()
    group_verbose.add_argument("-v", type=int, default=5, help="Verbose count.")
    group_verbose.add_argument("-q", "--quiet", action="store_true", help="Quiet output. Just display necessary information.")
    parsed_args = argparser.parse_args()

    if parsed_args.quiet:
        LOGGER.set_level(LEVEL_WARN)
    else:
        LOGGER.set_level(parsed_args.v)

    if not parsed_args.quiet:
        print_banner()

    try:
        main_proxy = Proxy("0.0.0.0", 8081, parsed_args.source)
        main_proxy.run()
    except CompilerException as e:
        LOGGER.ERROR(e)
        return

if __name__ == '__main__':
    main()
